---
title: "Nancy Hammond PhD"
author: ""
#date: "`r Sys.Date()`"
output:
  pdf_document: default
  html_document: default
---



---

**Nancy Hammond, Ph.D.**
Chicago, IL 60661 | 312.709.5328 | nahammond@uchicago.edu | GitHub: @nhammond36 | LinkedIn: [LinkedIn Profile](https://www.linkedin.com/in/nahammondphd) | Portfolio: [Personal Website](https://sites.google.com/site/nahammond/home/)

---

**ECONOMIST | QUANTITATIVE RESEARCH**

---

Experienced economist and quantitative researcher with a focus on fixed income, monetary policy, and risk management. A seasoned finance professional with over 15 years of industry experience, including a decade as an Economist/Quantitative Researcher. Proficient in financial mathematics, risk management, fixed income,  deep learning,  machine learning, AI, monetary policy and repo markets.  Programming languages C++, Matlab, Python, and R. Skilled in credit and operational risk, settlement, counterparty credit and market risk. Historical VaR, multi-factor bond returns, volatility, and liquidity risk models. Yield curve and fixed income models 

**ACHIEVEMENTS:**
- PCA estimates of term structure of US Treasury security risk premia from latent and macroeconomic factors.
- Estimated volatility model of overnight policy and wholesale money market rate response to FOMC policy changes.
- Developed operational risk LDA model, Matlab code, documentation.
- Stevanovich Center for Financial Mathematics, University of Chicago, 2018 SoFiE Certificate in Machine Learning and Finance
---

**STRENGTHS COMPETENCIES:**
- University of Chicago PhD Economist | Macrofinance | Advanced quantitative methods | Econometrics | Statistics | Probability | Financial mathematics | Deep learning, AI | Monetary policy | Repo, credit funding | Risk mitigation model development & validation credit, operational risk | counterparty credit risk, settlement risk, liquidity risk, market risk | Software: R, Matlab, C++, Stata, Python, GitHub, LaTeX.
- Effective communication with multiple stakeholders, well-organized, lifelong learner.

---

**PROFESSIONAL EXPERIENCE**

---

**Economist/Founder, qaEconomics - Financial and Economic Consulting**
January 2020 - Present
- Estimated term structure of US Treasury security risk premia using PCA with latent and macroeconomic factors.
Estimated volatility model of overnight policy and wholesale money market rate response to FOMC policy changes.
- Developed management tools for counterparty risk, market-to-market, margin, and stress testing.
- Developed historical VaR, Monte Carlo VaR, Multi-Factor Risk Models, Stressed VaR, and Liquidity Risk models.
- Prepared a macroeconomic report on the United Arab Emirates.
---

**Lecturer, Corporate Finance, DePaul University - Driehaus School of Business**
January 2020 - July 2022
- Taught corporate finance, risk assessment, return on investments, cost of capital, capital structure, and the relationship between interest rates and the economy.
- Instructed on creating and analyzing financial models for decision-making.
- Introduced the concept of shadow banking and its implications for financial system stability.

---

**Managing Consultant, Risk Management Advisory, KPMG**
September 2016 - July 2017
- Developed credit risk and operational risk models for global systemically important banks (G-SIBs).
- Worked on equity margin loss models and provided guidance on prepayment models for mortgage securities.
- Presented best practices for operational risk mitigation.

---

**Senior Quantitative Researcher, Risk, Protiviti**
March 2013 - September 2015
- Quantified and submitted capital adequacy and liquidity assessments for G-SIB clients for CCAR reports.
- Conducted operational risk modeling and stress tests for Federal Reserve risk scenarios.
- Developed a Poisson regression model for loss frequencies in operational risk LDA models.

---

**Managing Consultant, Energy Efficiency, Navigant - Chicago, IL**
January 2011 - November 2012
- Created strategies, models, and analyses to optimize energy consumption and demand.
- Measured response to energy efficiency equipment and energy pricing and incentives.

---

**Economist, RCF Economic and Financial Consulting**
April 2006 - May 2010
- Provided strategy, trends, and sector-specific analysis for clients’ decision-making.
- Developed Loss Distribution Approach (LDA) operational risk models for G-SIBs and conducted vector autoregression and error correction analyses.
- Prepared white paper on price and quantity indices.

---

**Economist, Argonne National Laboratory**
January 2001 - March 2006
- Stochastic frontier models of energy use cost functions for corn product producers to estimate the  Energy Performance Indicator (EPI) of the Environmental Protection Agency’s (EPA) Energy Star program.
- Researched energy use data from various sources and visualized results to communicate insights.

---

**Assistant Professor, Northwestern University**
September 2000 - September 2004
- Developed instructional materials for courses in international finance, money/banking, economic growth, and demography.
- Mentored students and employed innovative teaching methods.

---

**EDUCATION**

- Ph.D. in Economics, University of Chicago - Chicago, IL (March 2016)
- University of Chicago Booth Asset Pricing, Empirical Finance, Stochastic Calculus
- Stevanovich Center for Financial Mathematics, University of Chicago, 2018 SoFiE Certificate in Machine Learning and Finance

---

**ONLINE COURSES**

- Coursera: [The Global Financial Crisis, 5/15/2017](https://coursera.org/verify/X7K8356TEGMU)
- Coursera: [Neural Networks and Deep Learning, 9/12/2021](https://coursera.org/verify/R9K2YJY7HTMY)
- Coursera: [Improving Deep Neural Networks: Hyperparameter Tuning, Regularization and Optimization
12/24/2022] (https://coursera.org/verify/5PNH9DALTUNB)
- Coursera: Deep Learning Specialization. https://www.coursera.org/specializations/deep-learning
            Completing this specialization
- Coursers: Guided Tour of Machine Learning in Finance. completing this specialization       
            https://www.coursera.org/learn/guided-tour-machine-learning-finance/
- Coursera: Python and Statistics for Financial Analysis. completing this   c  
            course.https://www.coursera.org/learn/python-statistics-financial-analysis/
- Coursera: Object-Oriented Data Structures in C++ (on going)
---

**WORKING PAPERS**

- Factor and affine models of the term structure of Treasury securities risk premiums.
- Volatility response of overnight funding rates to FOMC policy.
- Coordinated monetary and fiscal policy under different transaction technologies.
 The impact of active monetary policy and state contingent net bond sales.
- Dissertation: Education and reduced mortality in pre-industrial Britain.

---

**AFFILIATIONS**

- American Economic Association
- American Finance Association
- Old St Pat’s Immigration Committee
- WILD: Women in Listed Derivatives
- Women in Conflict Zones

---

**LANGUAGES**

- Arabic: Limited working
- French: Professional working
- Russian: Limited working
- Spanish: Professional working